openapi: 3.0.0
info:
  title: 陌生人聊天交友App
  version: 1.0.0

tags:
  - name: 验证码
    description: 验证码相关接口
  - name: 用户
    description: 用户相关接口
  - name: 资源
    description: 资源相关接口

paths:

  /verifications/sendCode:
    post:
      summary: 发送验证码
      tags:
        - 验证码
      requestBody:
        content:
          application/json:
            schema:
              required:
                - mobile
              properties:
                mobile:
                  type: string
                  description: 手机号码
      responses:
        200:
          description: 发送成功
        400:
          description: 发送失败
          content:
            application/json:
              schema:
                required:
                  - message
                properties:
                  message:
                    type: string
                    description: 错误信息

  /verifications/verifyCode:
    post:
      summary: 验证码验证
      tags:
        - 验证码
      requestBody:
        content:
          application/json:
            schema:
              required:
                - mobile
                - code
              properties:
                mobile:
                  type: string
                  description: 手机号码
                code:
                  type: string
                  description: 验证码
                longitude:
                  type: string
                  format: float
                  description: 经度
                latitude:
                  type: string
                  format: float
                  description: 纬度
      responses:
        200:
          description: 验证成功并且手机号已注册,返回登录jwt和用户信息
          content:
            application/json:
              schema:
                required:
                  - token
                  - userId
                  - gender
                  - birthday
                  - avatar
                properties:
                  token:
                    type: string
                    description: 登录jwt
                  userId:
                    type: integer
                  gender:
                    type: string
                    description: 性别
                  birthday:
                    type: string
                    format: date
                    description: 生日
                  avatar:
                    type: string
                    description: 头像URL
                  giftsReceived:
                    type: integer
                    description: 收到的礼物数
                  username:
                    type: string
                    description: 用户名
                  city:
                    type: string
                    description: 城市
                  followingCount:
                    type: integer
                    description: 我关注的用户数
                  followersCount:
                    type: integer
                    description: 关注我的用户数
                  visitorsCount:
                    type: integer
                    description: 我的访客数
                  freeHeatsLeft:
                    type: integer
                    description: 免费加热次数
                  coinBalance:
                    type: integer
                    description: 金币余额

        201:
          description: 验证成功但是手机号未注册,需要进入注册流程

        400:
          description: 验证码错误
          content:
            application/json:
              schema:
                required:
                  - message
                properties:
                  message:
                    type: string
                    description: 错误信息

  /users/register:
    post:
      summary: 用户注册
      tags:
        - 用户
      requestBody:
        content:
          application/json:
            schema:
              required:
                - mobile
                - gender
                - birthday
                - avatar
              properties:
                mobile:
                  type: string
                  description: 手机号码
                gender:
                  type: string
                  description: 性别
                birthday:
                  type: string
                  format: date
                  description: 生日
                avatar:
                  type: string
                  description: 头像
                longitude:
                  type: string
                  format: float
                  description: 经度
                latitude:
                  type: string
                  format: float
                  description: 纬度
      responses:
        200:
          description: 注册成功
          content:
            application/json:
              schema:
                required:
                  - token
                  - userId
                properties:
                  token:
                    type: string
                    description: 登录jwt
                  userId:
                    type: integer
                    description: 用户ID

        400:
          description: 注册失败
          content:
            application/json:
              schema:
                required:
                  - message
                properties:
                  message:
                    type: string
                    description: 错误信息

  /uploadAvatar:
    post:
      summary: 上传头像
      tags:
        - 资源
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - avatar
              properties:
                avatar:
                  type: string
                  format: binary
                  description: 头像图片
            encoding:
              avatar:
                contentType: image/*
      responses:
        200:
          description: 上传成功
          content:
            application/json:
              schema:
                required:
                  - url
                properties:
                  url:
                    type: string
                    description: 头像URL

        400:
          description: 上传失败
          content:
            application/json:
              schema:
                required:
                  - message
                properties:
                  message:
                    type: string
                    description: 错误信息
